version: '3'
services:

  scala-ui:
    image: scala/ui:latest
    ports:
      - "3000:80"
    depends_on:
      - scala-api
    links:
      - "scala-api"
    restart: 'always'
    container_name: scala-ui
  scala-api:
    image: scala/api:latest
    ports:
      - "8080:8080"
    restart: 'always'
    env_file:
      - .env
    container_name: scala-api