export const INIT_APP = 'INIT_APP';

export const SET_WORKFLOW_FORM = 'SET_WORKFLOW_FORM';

export const CREATE_WORKFLOW = 'CREATE_WORKFLOW';

export const FETCHED_WORKFLOWS_AVAILABLE_SUCCESS = 'FETCHED_WORKFLOWS_AVAILABLE_SUCCESS';

export const FETCHED_WORKFLOWS_AVAILABLE_FAILED = 'FETCHED_WORKFLOWS_AVAILABLE_FAILED';

export const FETCH_CONNECTIONS = 'FETCH_CONNECTIONS';

export const FETCHED_CONNECTIONS_SUCCESS = 'FETCHED_CONNECTIONS_SUCCESS';

export const FETCHED_CONNECTIONS_FAILED = 'FETCHED_CONNECTIONS_FAILED';

export const FETCHED_WORKFLOW_TEMPLATES_SUCCESS = 'FETCHED_WORKFLOW_TEMPLATES_SUCCESS';

export const FETCHED_WORKFLOW_TEMPLATES_FAILED = 'FETCHED_WORKFLOW_TEMPLATES_FAILED';

export const FETCHED_SCHEDULES_SUCCESS = 'FETCHED_SCHEDULES_SUCCESS';

export const FETCHED_SCHEDULES_FAILED = 'FETCHED_SCHEDULES_FAILED';

export const FETCH_JOBS = 'FETCH_JOBS';

export const FETCHED_JOBS_FAILED = 'FETCHED_JOBS_FAILED';

export const FETCHED_JOBS_SUCCESS = 'FETCHED_JOBS_SUCCESS';

export const CREATE_WORKFLOW_FAILED = 'CREATE_WORKFLOW_FAILED';

export const CREATE_WORKFLOW_SUCCESS = 'CREATE_WORKFLOW_SUCCESS';

export const FETCHED_JOBS_STATUS_FAILED = 'FETCHED_JOBS_STATUS_FAILED';

export const FETCHED_JOBS_STATUS_SUCCESS = 'FETCHED_JOBS_STATUS_SUCCESS';

export const DELETE_WORKFLOW = 'DELETE_WORKFLOW';

export const DELETE_WORKFLOW_SUCCESS = 'DELETE_WORKFLOW_SUCCESS';

export const DELETE_WORKFLOW_FAILED = 'DELETE_WORKFLOW_FAILED';

export const RUN_WORKFLOW = 'RUN_WORKFLOW';

export const RUN_WORKFLOW_SUCCESS = 'RUN_WORKFLOW_SUCCESS';

export const RUN_WORKFLOW_FAILED = 'RUN_WORKFLOW_FAILED';

export const CREATE_SCHEDULE = 'CREATE_SCHEDULE';

export const CREATE_SCHEDULE_SUCCESS = 'CREATE_SCHEDULE_SUCCESS';

export const CREATE_SCHEDULE_FAILED = 'CREATE_SCHEDULE_FAILED';

export const EDIT_SCHEDULE = 'EDIT_SCHEDULE';

export const EDIT_SCHEDULE_SUCCESS = 'EDIT_SCHEDULE_SUCCESS';

export const EDIT_SCHEDULE_FAILED = 'EDIT_SCHEDULE_FAILED';

export const DELETE_SCHEDULE = 'DELETE_SCHEDULE';

export const DELETE_SCHEDULE_SUCCESS = 'DELETE_SCHEDULE_SUCCESS';

export const DELETE_SCHEDULE_FAILED = 'DELETE_SCHEDULE_FAILED';

export const DOWNLOAD_KEY_PAIR = 'DOWNLOAD_KEY_PAIR';

export const DOWNLOAD_KEY_PAIR_SUCCESS = 'DOWNLOAD_KEY_PAIR_SUCCESS';

export const DOWNLOAD_KEY_PAIR_FAILED = 'DOWNLOAD_KEY_PAIR_FAILED';

export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';

export const DELETE_CONNECTION= 'DELETE_CONNECTION';

export const DELETE_CONNECTION_SUCCESS = 'DELETE_CONNECTION_SUCCESS';

export const DELETE_CONNECTION_FAILED = 'DELETE_CONNECTION_FAILED';

export const CREATE_CONNECTION= 'CREATE_CONNECTION';

export const CREATE_CONNECTION_SUCCESS = 'CREATE_CONNECTION_SUCCESS';

export const CREATE_CONNECTION_FAILED = 'CREATE_CONNECTION_FAILED';

export const FETCHED_DESKTOPS_SUCCESS = 'FETCHED_DESKTOPS_SUCCESS';

export const FETCHED_DESKTOPS_FAILED = 'FETCHED_DESKTOPS_FAILED';

export const CREATE_DESKTOP = 'CREATE_DESKTOP';

export const CREATE_DESKTOP_SUCCESS = 'CREATE_DESKTOP_SUCCESS';

export const CREATE_DESKTOP_FAILED = 'CREATE_DESKTOP_FAILED';

export const DELETE_DESKTOP = 'DELETE_DESKTOP';

export const DELETE_DESKTOP_SUCCESS = 'DELETE_DESKTOP_SUCCESS';

export const DELETE_DESKTOP_FAILED = 'DELETE_DESKTOP_FAILED';

export const PAUSE_DESKTOP = 'PAUSE_DESKTOP';

export const PAUSE_DESKTOP_SUCCESS = 'PAUSE_DESKTOP_SUCCESS';

export const PAUSE_DESKTOP_FAILED = 'PAUSE_DESKTOP_FAILED';

export const RESUME_DESKTOP = 'RESUME_DESKTOP';

export const RESUME_DESKTOP_SUCCESS = 'RESUME_DESKTOP_SUCCESS';

export const RESUME_DESKTOP_FAILED = 'RESUME_DESKTOP_FAILED';

export const PROCESS_QUEUE = 'PROCESS_QUEUE';

export const PUSH_MESSAGE = 'PUSH_MESSAGE';

export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';

export const EDIT_WORKFLOW = 'EDIT_WORKFLOW';

export const EDIT_WORKFLOW_SUCCESS = 'EDIT_WORKFLOW_SUCCESS';

export const EDIT_WORKFLOW_FAILED = 'EDIT_WORKFLOW_FAILED';

export const FETCH_FILE = 'FETCH_FILE';

export const FETCHED_FILE_FAILED = 'FETCHED_FILE_FAILED';

export const FETCHED_FILE_SUCCESS = 'FETCHED_FILE_SUCCESS';

export const FETCH_FOLDER = 'FETCH_FOLDER';

export const FETCHED_FOLDER_FAILED = 'FETCHED_FOLDER_FAILED';

export const FETCHED_FOLDER_SUCCESS = 'FETCHED_FOLDER_SUCCESS';

export const CLEAR_FILE = 'CLEAR_FILE';

export const CREATE_FOLDER = 'CREATE_FOLDER';

export const CREATE_FOLDER_SUCCESS = 'CREATE_FOLDER_SUCCESS';

export const CREATE_FOLDER_FAILED = 'CREATE_FOLDER_FAILED';

export const SAVE_FILE = 'SAVE_FILE';

export const SAVE_FILE_SUCCESS = 'SAVE_FILE_SUCCESS';

export const SAVE_FILE_FAILED = 'SAVE_FILE_FAILED';

export const UPDATE_CODE = 'UPDATE_CODE';

export const DOWNLOAD_FILE = 'DOWNLOAD_FILE';

export const DOWNLOAD_FILE_SUCCESS = 'DOWNLOAD_FILE_SUCCESS';

export const DOWNLOAD_FILE_FAILED = 'DOWNLOAD_FILE_FAILED';

export const UPLOAD_FILES = 'UPLOAD_FILES';

export const UPLOAD_FILES_SUCCESS = 'UPLOAD_FILES_SUCCESS';

export const UPLOAD_FILES_FAILED = 'UPLOAD_FILES_FAILED';

export const DELETE_FILE = 'DELETE_FILE';

export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS';

export const DELETE_FILE_FAILED = 'DELETE_FILE_FAILED';

export const TERMINATE_JOB = 'TERMINATE_JOB';

export const TERMINATE_JOB_SUCCESS = 'TERMINATE_JOB_SUCCESS';

export const TERMINATE_JOB_FAILED = 'TERMINATE_JOB_FAILED';

export const CREATE_DESKTOP_JOB = 'CREATE_DESKTOP_JOB';

export const CREATE_DESKTOP_JOB_SUCCESS = 'CREATE_DESKTOP_JOB_SUCCESS';

export const CREATE_DESKTOP_JOB_FAILED = 'CREATE_DESKTOP_JOB_FAILED';

export const DESKTOP_NOT_READY = 'DESKTOP_NOT_READY';

export const LAUNCHED_DESKTOP = 'LAUNCHED_DESKTOP';

export const RENAME_FILE = 'RENAME_FILE';

export const RENAME_FILE_SUCCESS = 'RENAME_FILE_SUCCESS';

export const RENAME_FILE_FAILED = 'RENAME_FILE_FAILED';

export const PROMPT_JOB_DESKTOP_DNE = 'PROMPT_JOB_DESKTOP_DNE';

export const GET_STD_ERR = 'GET_STD_ERR';

export const GET_STD_ERR_SUCCESS = 'GET_STD_ERR_SUCCESS';

export const GET_STD_ERR_FAILED = 'GET_STD_ERR_FAILED';

export const GET_STD_OUT = 'GET_STD_OUT';

export const GET_STD_OUT_SUCCESS = 'GET_STD_OUT_SUCCESS';

export const GET_STD_OUT_FAILED = 'GET_STD_OUT_FAILED';

export const REGISTER = 'REGISTER';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const REGISTER_FAILED = 'REGISTER_FAILED';

export const LOG_IN = 'LOG_IN';

export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';

export const LOG_IN_FAILED = 'LOG_IN_FAILED';

export const LOG_OUT = 'LOG_OUT';

export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';

export const LOG_OUT_FAILED = 'LOG_OUT_FAILED';

export const VERIFY = 'VERIFY';

export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';

export const VERIFY_FAILED = 'VERIFY_FAILED';

export const FETCH_LOCAL_COGNITO_USER = 'FETCH_LOCAL_COGNITO_USER';

export const FETCH_LOCAL_COGNITO_USER_SUCCESS = 'FETCH_LOCAL_COGNITO_USER_SUCCESS';

export const FETCH_LOCAL_COGNITO_USER_FAILED = 'FETCH_LOCAL_COGNITO_USER_FAILED';

export const GET_JOB_METRICS = 'GET_JOB_METRICS';

export const GET_JOB_METRICS_SUCCESS = 'GET_JOB_METRICS_SUCCESS';

export const GET_JOB_METRICS_FAILED = 'GET_JOB_METRICS_FAILED';

export const FETCHED_AUTH_CONFIG_SUCCESS = 'FETCHED_AUTH_CONFIG_SUCCESS';

export const FETCHED_AUTH_CONFIG_FAILED = 'FETCHED_AUTH_CONFIG_FAILED';

export const INITIALIZE_DIRECTORIES_SUCCESS = 'INITIALIZE_DIRECTORIES_SUCCESS';

export const INITIALIZE_DIRECTORIES_FAILED = 'INITIALIZE_DIRECTORIES_FAILED';

export const NEEDS_VERIFICATION = 'NEEDS_VERIFICATION';

export const RESEND_CODE = 'RESEND_CODE';

export const RESEND_CODE_SUCCESS = 'RESEND_CODE_SUCCESS';

export const RESEND_CODE_FAILED = 'RESEND_CODE_FAILED';

export const IMPERSONATE_USER = 'IMPERSONATE_USER';

export const IMPERSONATE_USER_SUCCESS = 'IMPERSONATE_USER_SUCCESS';

export const IMPERSONATE_USER_FAILED = 'IMPERSONATE_USER_FAILED';

export const IMPERSONATE_USER_CLEAR = 'IMPERSONATE_USER_CLEAR';

export const FETCHED_COMPUTES_FAILED = 'FETCHED_COMPUTES_FAILED'

export const FETCHED_COMPUTES_SUCCESS = 'FETCHED_COMPUTES_SUCCESS'

export const FETCH_JOB_PERFORMANCE = 'FETCH_JOB_PERFORMANCE'

export const FETCH_JOB_PERFORMANCE_SUCCESS = 'FETCH_JOB_PERFORMANCE_SUCCESS'

export const FETCH_JOB_PERFORMANCE_FAILED = 'FETCH_JOB_PERFORMANCE_FAILED'

export const SHOW_STANDARD_OUT = 'SHOW_STANDARD_OUT'

export const SHOW_STANDARD_ERR = 'SHOW_STANDARD_ERR'

export const CLOSE_STANDARD_MODAL = 'CLOSE_STANDARD_MODAL'

export const FETCH_DAILY_COSTS = 'FETCH_DAILY_COSTS';

export const FETCHED_DAILY_COSTS_SUCCESS = 'FETCHED_DAILY_COSTS_SUCCESS';

export const FETCHED_DAILY_COSTS_FAILED = 'FETCHED_DAILY_COSTS_FAILED';

export const RESTART_JOB = 'RESTART_JOB';

export const RESTART_JOB_SUCCESS = 'RESTART_JOB_SUCCESS';

export const RESTART_JOB_FAILED = 'RESTART_JOB_FAILED';

export const CLONE_WORKFLOW = 'CLONE_WORKFLOW';

export const CLONE_WORKFLOW_SUCCESS = 'CLONE_WORKFLOW_SUCCESS';

export const CLONE_WORKFLOW_FAILED = 'CLONE_WORKFLOW_FAILED';

export const DROP_FAILED = 'DROP_FAILED';

export const UNKNOWN_ERROR = 'UNKNOWN_ERROR';

export const GET_COMPUTE_COST = 'GET_COMPUTE_COST';

export const GET_COMPUTE_COST_FAILED = 'GET_COMPUTE_COST_FAILED';

export const GET_COMPUTE_COST_SUCCESS = 'GET_COMPUTE_COST_SUCCESS';
