export const INIT_APP = 'INIT_APP';

export const SET_WORKFLOW_FORM = 'SET_WORKFLOW_FORM';

export const SUBMIT_NEW_WORKFLOW = 'SUBMIT_NEW_WORKFLOW';

export const FETCHED_WORKFLOWS_AVAILABLE_SUCCESS = 'FETCHED_WORKFLOWS_AVAILABLE_SUCCESS';

export const FETCHED_WORKFLOWS_AVAILABLE_FAILED = 'FETCHED_WORKFLOWS_AVAILABLE_FAILED';

export const FETCHED_CONNECTIONS_SUCCESS = 'FETCHED_CONNECTIONS_SUCCESS';

export const FETCHED_CONNECTIONS_FAILED = 'FETCHED_CONNECTIONS_FAILED';

export const FETCHED_WORKFLOW_TEMPLATES_SUCCESS = 'FETCHED_WORKFLOW_TEMPLATES_SUCCESS';

export const FETCHED_WORKFLOW_TEMPLATES_FAILED = 'FETCHED_WORKFLOW_TEMPLATES_FAILED';

export const FETCHED_SCHEDULES_SUCCESS = 'FETCHED_SCHEDULES_SUCCESS';

export const FETCHED_SCHEDULES_FAILED = 'FETCHED_SCHEDULES_FAILED';

export const FETCHED_JOBS_FAILED = 'FETCHED_JOBS_FAILED';

export const FETCHED_JOBS_SUCCESS = 'FETCHED_JOBS_SUCCESS';

export const SUBMIT_WORKFLOW_FAILED = 'SUBMIT_WORKFLOW_FAILED';

export const SUBMIT_WORKFLOW_SUCCESS = 'SUBMIT_WORKFLOW_SUCCESS';

export const FETCHED_JOBS_STATUS_FAILED = 'FETCHED_JOBS_STATUS_FAILED';

export const FETCHED_JOBS_STATUS_SUCCESS = 'FETCHED_JOBS_STATUS_SUCCESS';

export const DELETE_WORKFLOW = 'DELETE_WORKFLOW';

export const DELETE_WORKFLOW_SUCCESS = 'DELETE_WORKFLOW_SUCCESS';

export const DELETE_WORKFLOW_FAILED = 'DELETE_WORKFLOW_FAILED';

export const RUN_WORKFLOW = 'RUN_WORKFLOW';

export const RUN_WORKFLOW_SUCCESS = 'RUN_WORKFLOW_SUCCESS';

export const RUN_WORKFLOW_FAILED = 'RUN_WORKFLOW_FAILED';

export const CREATE_SCHEDULE = 'CREATE_SCHEDULE';

export const CREATE_SCHEDULE_SUCCESS = 'CREATE_SCHEDULE_SUCCESS';

export const CREATE_SCHEDULE_FAILED = 'CREATE_SCHEDULE_FAILED';

export const DELETE_SCHEDULE = 'DELETE_SCHEDULE';

export const DELETE_SCHEDULE_SUCCESS = 'DELETE_SCHEDULE_SUCCESS';

export const DELETE_SCHEDULE_FAILED = 'DELETE_SCHEDULE_FAILED';

export const DOWNLOAD_KEY_PAIR = 'DOWNLOAD_KEY_PAIR';

export const DOWNLOAD_KEY_PAIR_SUCCESS = 'DOWNLOAD_KEY_PAIR_SUCCESS';

export const DOWNLOAD_KEY_PAIR_FAILED = 'DOWNLOAD_KEY_PAIR_FAILED';

export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';

export const DELETE_CONNECTION= 'DELETE_CONNECTION';

export const DELETE_CONNECTION_SUCCESS = 'DELETE_CONNECTION_SUCCESS';

export const DELETE_CONNECTION_FAILED = 'DELETE_CONNECTION_FAILED';

export const CREATE_CONNECTION= 'CREATE_CONNECTION';

export const CREATE_CONNECTION_SUCCESS = 'CREATE_CONNECTION_SUCCESS';

export const CREATE_CONNECTION_FAILED = 'CREATE_CONNECTION_FAILED';

export const FETCHED_DESKTOPS_SUCCESS = 'FETCHED_DESKTOPS_SUCCESS';

export const FETCHED_DESKTOPS_FAILED = 'FETCHED_DESKTOPS_FAILED';

export const CREATE_DESKTOP = 'CREATE_DESKTOP';

export const CREATE_DESKTOP_SUCCESS = 'CREATE_DESKTOP_SUCCESS';

export const CREATE_DESKTOP_FAILED = 'CREATE_DESKTOP_FAILED';

export const DELETE_DESKTOP = 'DELETE_DESKTOP';

export const DELETE_DESKTOP_SUCCESS = 'DELETE_DESKTOP_SUCCESS';

export const DELETE_DESKTOP_FAILED = 'DELETE_DESKTOP_FAILED';
